<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit9016a13f57e39e6173ebf57a3b7654c0
{
    public static $prefixLengthsPsr4 = array (
        'T' => 
        array (
            'Tree\\' => 5,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Tree\\' => 
        array (
            0 => __DIR__ . '/..' . '/chj/tree/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit9016a13f57e39e6173ebf57a3b7654c0::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit9016a13f57e39e6173ebf57a3b7654c0::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
